# Generated by Django 4.0.6 on 2023-09-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=128)),
                ('composer_date', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('piece_voices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_filename', models.CharField(max_length=256)),
                ('absq', models.IntegerField()),
                ('base_note', models.IntegerField()),
                ('base_note_name', models.CharField(max_length=2)),
                ('reduced_chord', models.CharField(max_length=64)),
                ('full_chord', models.CharField(max_length=256)),
                ('voices', models.IntegerField()),
                ('bar', models.IntegerField()),
                ('beat', models.IntegerField()),
            ],
        ),
    ]
