# Generated by Django 4.0.6 on 2023-09-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('composer', models.CharField(max_length=128)),
                ('attributed_composer', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.RemoveField(
            model_name='point',
            name='piece_filename',
        ),
        migrations.AlterField(
            model_name='point',
            name='base_note_name',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='point',
            name='piece',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='redix.piece'),
            preserve_default=False,
        ),
    ]
