# Generated by Django 4.0.6 on 2023-09-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0002_piece_delete_metadata_remove_point_piece_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='piece',
        ),
        migrations.AddField(
            model_name='point',
            name='filename',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='absq',
            field=models.FloatField(),
        ),
    ]
