# Generated by Django 4.0.6 on 2023-09-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0003_remove_point_piece_point_filename_alter_point_absq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='attributed_composer',
        ),
    ]
