# Generated by Django 4.0.6 on 2023-09-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0004_remove_piece_attributed_composer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='filename',
            new_name='path',
        ),
    ]
