# Generated by Django 4.0.6 on 2023-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0008_alter_point_full_chord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='full_chord',
            field=models.CharField(max_length=64),
        ),
    ]
