# Generated by Django 4.0.6 on 2023-10-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0009_alter_point_full_chord'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='composer',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='full_chord',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='point',
            name='reduced_chord',
            field=models.CharField(max_length=128),
        ),
    ]
