# Generated by Django 4.0.6 on 2023-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0010_point_composer_alter_point_full_chord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='absq_mod4',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
