# Generated by Django 4.0.6 on 2023-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0011_point_absq_mod4'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
