# Generated by Django 4.0.6 on 2023-10-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0012_point_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='point',
            name='path',
        ),
        migrations.RemoveField(
            model_name='point',
            name='title',
        ),
        migrations.AddField(
            model_name='point',
            name='piece',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='redix.piece'),
            preserve_default=False,
        ),
    ]
