# Generated by Django 4.0.6 on 2023-10-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redix', '0013_remove_point_composer_remove_point_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='len_segment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
